project:
  type: website
  output-dir: docs

website:
  title: "Ran Xin Jiang"
  description:
    Personal website to showcase past projects and skill sets.
  site-url: "https://rxjiang12.github.io/PORTFOLIO/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: minty
    toc: false

editor:
  mode: source